# Generated by Django 2.0 on 2018-06-23 09:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orgnz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('1', '开发'), ('2', '运维'), ('3', '产品'), ('4', '测试')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('29fae4af-6d25-42e9-9aac-2295a095b61d'), editable=False, primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=30, verbose_name='姓名')),
                ('ID', models.BigIntegerField(max_length=50, unique=True, verbose_name='工号')),
                ('Group', models.ManyToManyField(to='download_excel.Orgnz', verbose_name='组织')),
            ],
        ),
        migrations.AddIndex(
            model_name='orgnz',
            index=models.Index(fields=['type'], name='type_idx'),
        ),
    ]
